"""Add duration_minutes and total_cost to parking_sessions

Revision ID: 1575ce886845
Revises: ad867413a088
Create Date: 2025-12-15 20:07:16.502096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1575ce886845'
down_revision: Union[str, None] = 'ad867413a088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('parking_sessions', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_sessions', 'total_cost')
    op.drop_column('parking_sessions', 'duration_minutes')
    # ### end Alembic commands ###
