"""Add estimated_cost to bookings

Revision ID: 858c32f188eb
Revises: 8afdbf74aaef
Create Date: 2025-12-15 20:47:18.164054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858c32f188eb'
down_revision: Union[str, None] = '8afdbf74aaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add estimated_cost column as nullable first
    op.add_column('bookings', sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE bookings SET estimated_cost = 0.00 WHERE estimated_cost IS NULL")

    # Now make it NOT NULL
    op.alter_column('bookings', 'estimated_cost', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'estimated_cost')
    # ### end Alembic commands ###
