"""Add is_admin field to customers

Revision ID: 8c64ecd615bf
Revises: 542d43dcf114
Create Date: 2025-12-08 16:05:24.913125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c64ecd615bf'
down_revision: Union[str, None] = '542d43dcf114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_admin')
    # ### end Alembic commands ###
