from app.schemas.customer import (
    CustomerBase,
    CustomerCreate,
    CustomerUpdate,
    CustomerResponse,
    CustomerLogin,
)
from app.schemas.vehicle import (
    VehicleBase,
    VehicleCreate,
    VehicleUpdate,
    VehicleResponse,
)
from app.schemas.booking import (
    BookingBase,
    BookingCreate,
    BookingUpdate,
    BookingResponse,
    BookingStatusUpdate,
)
from app.schemas.parking import (
    TariffPlanBase,
    TariffPlanCreate,
    TariffPlanResponse,
    ParkingZoneBase,
    ParkingZoneCreate,
    ParkingZoneUpdate,
    ParkingZoneResponse,
    ParkingSpotBase,
    ParkingSpotCreate,
    ParkingSpotUpdate,
    ParkingSpotResponse,
    AvailabilityRequest,
    AvailabilityResponse,
)
from app.schemas.session import (
    ParkingSessionBase,
    ParkingSessionCreate,
    ParkingSessionEnd,
    ParkingSessionResponse,
)
from app.schemas.payment import (
    PaymentBase,
    PaymentCreate,
    PaymentUpdate,
    PaymentResponse,
)
from app.schemas.token import Token, TokenData

__all__ = [
    "CustomerBase",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CustomerLogin",
    "VehicleBase",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleResponse",
    "BookingBase",
    "BookingCreate",
    "BookingUpdate",
    "BookingResponse",
    "BookingStatusUpdate",
    "TariffPlanBase",
    "TariffPlanCreate",
    "TariffPlanResponse",
    "ParkingZoneBase",
    "ParkingZoneCreate",
    "ParkingZoneUpdate",
    "ParkingZoneResponse",
    "ParkingSpotBase",
    "ParkingSpotCreate",
    "ParkingSpotUpdate",
    "ParkingSpotResponse",
    "AvailabilityRequest",
    "AvailabilityResponse",
    "ParkingSessionBase",
    "ParkingSessionCreate",
    "ParkingSessionEnd",
    "ParkingSessionResponse",
    "PaymentBase",
    "PaymentCreate",
    "PaymentUpdate",
    "PaymentResponse",
    "Token",
    "TokenData",
]
